title: CaoTien
description: "Hello World"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.jpeg"

# Social Links
email: trqt2003@gmail.com
github_username: taitq
twitter_username: Caotien010
instagram_username: trqt2003
linkedin_username: tai-tran-quang-078b2b210
facebook_username: tai.tranquang.1293


baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"
      comments: true   # change to false to default to comments off site-wide
      published: true  # default to published

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
